name: email_digest_generator
description: A simple weeklly digest generator base on Pocket links
version: 0.0.1
author: Ne4istb <anechytailov@gmail.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  redstone: '^0.6.1'
  mailer: '^0.8.12'
  mongo_dart: '0.2.5-beta'
  http: '^0.11.3+2'
  pocket_client: any
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
