name: EmailDigestGenerator
description: A simple weeklly digest generator base on Pocket links
version: 0.0.1
author: Ne4istb <anechytailov@gmail.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
